-- Run this file once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  name text not null default '',
  role text not null default 'student' check (role in ('student', 'admin')),
  created_at timestamptz not null default now()
);

create table public.courses (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null default '',
  content jsonb not null default '{"sections":[]}'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.course_enrollments (
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, course_id)
);

create table public.exams (
  id text primary key,
  title text not null,
  payload jsonb not null default '{}'::jsonb,
  published boolean not null default true,
  created_at timestamptz not null default now()
);

create table public.lesson_progress (
  user_id uuid not null references public.profiles(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  lesson_id text not null,
  completed_at timestamptz not null default now(),
  primary key (user_id, course_id, lesson_id)
);

create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from profiles where id = auth.uid() and role = 'admin') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public
as $$ begin
  insert into profiles(id, email, name)
  values(new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'name', ''));
  return new;
end $$;

create trigger on_auth_user_created after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table profiles enable row level security;
alter table courses enable row level security;
alter table course_enrollments enable row level security;
alter table exams enable row level security;
alter table lesson_progress enable row level security;

create policy "profile self or admin read" on profiles for select to authenticated
using (id = auth.uid() or is_admin());
create policy "admin manages profiles" on profiles for update to authenticated
using (is_admin()) with check (is_admin());

create policy "public reads course catalog" on courses for select to anon
using (published);
create policy "enrolled reads courses" on courses for select to authenticated
using (is_admin() or exists(select 1 from course_enrollments e where e.course_id = courses.id and e.user_id = auth.uid()));
create policy "admin inserts courses" on courses for insert to authenticated with check (is_admin());
create policy "admin updates courses" on courses for update to authenticated using (is_admin()) with check (is_admin());
create policy "admin deletes courses" on courses for delete to authenticated using (is_admin());

create policy "self reads enrollment" on course_enrollments for select to authenticated
using (user_id = auth.uid() or is_admin());
create policy "admin manages enrollments" on course_enrollments for all to authenticated
using (is_admin()) with check (is_admin());

create policy "authenticated reads exams" on exams for select to authenticated using (published or is_admin());
create policy "admin manages exams" on exams for all to authenticated using (is_admin()) with check (is_admin());

create policy "self reads progress" on lesson_progress for select to authenticated using (user_id = auth.uid() or is_admin());
create policy "self writes progress" on lesson_progress for insert to authenticated
with check (user_id = auth.uid() and exists(select 1 from course_enrollments e where e.user_id = auth.uid() and e.course_id = lesson_progress.course_id));
create policy "self deletes progress" on lesson_progress for delete to authenticated using (user_id = auth.uid());

-- Anonymous visitors may see marketing fields, never the protected JSON content.
revoke select on public.courses from anon;
grant select (id, title, description, published) on public.courses to anon;

-- Catalog view deliberately excludes protected course content.
create view public.course_catalog with (security_invoker = true) as
select id, title, description
from courses where published;
grant select on public.course_catalog to anon, authenticated;
